---
title: "RFP variable availability"
author: "Hilaire et al. (2022)"
date: "09-08-2022"
output: 
  word_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_libraries, error=FALSE, message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(rlang)
library(lazyeval)
library(kableExtra)
library(officer)
library(officedown)
library(flextable)
```

```{r load_functions, error=FALSE, message=FALSE, warning=FALSE, include=FALSE}
format_table_summary <- function(i_table, i_sector_escaped, i_check, i_equations) {
  
  out <- i_table
  
  for (kvar in grep(i_sector_escaped, names(i_check$`equation information`), value=T)) {
    # Get equation and variable information
    eq_info <- i_check$`equation information`[[kvar]]
    eq_vars <- names(i_check$`equation information`[[kvar]])
    
    # Get original equation definition
    v_rfp      <- i_equations$RFP[which(gsub("`", "", i_equations$lhs) == kvar)]
    
    v_equation <- i_equations$rhs[which(gsub("`", "", i_equations$lhs) == kvar)]
    
    v_subsector <- gsub(paste0("Diagnostics\\|RFP\\|",v_rfp,"\\|"), "", kvar)
    
    # v_equation <- gsub("*", "&#215;", v_equation, fixed = TRUE) %>% 
    #   gsub("+", "&#43;",   ., fixed = TRUE) #%>% 
    #   #gsub("-", "&#8722;", ., fixed = TRUE) %>% 
    #   #gsub("/", "&#247;",  ., fixed = TRUE) 
    
    # Loop over equation variables and format text equation
    # TODO: split equation into elements, apply gsub and recompose
    # for (keqvar in eq_vars) {
    #   #v_eqvar_escaped <- gsub("\\|", "\\\\|", keqvar)
    #   if (eq_info[[keqvar]]$status == "Fully available") {
    #     v_equation <- gsub(paste0("`", keqvar, "`"), paste0("<span style='color: blue'>`", keqvar, "`</span></br>"), v_equation, fixed = TRUE)
    #   }
    #   if (eq_info[[keqvar]]$status == "Partially available") {
    #     v_equation <- gsub(paste0("`", keqvar, "`"), paste0("<span style='color: orange'>`", keqvar, "`</span></br>"), v_equation, fixed = TRUE)
    #   }
    #   if (eq_info[[keqvar]]$status == "Unavailable") {
    #     v_equation <- gsub(paste0("`", keqvar, "`"), paste0("<span style='color: red'>`", keqvar, "`</span></br>"), v_equation, fixed = TRUE)
    #   }
    # }
    
    # v_equation <- gsub("_", "\\\\_", v_equation) %>%
    #               gsub("+", "+\n", ., fixed = TRUE) %>%
    #               #gsub("-", "-\n", ., fixed = TRUE) #%>%
    #               gsub("*", "*\n", ., fixed = TRUE) #%>%
    #               #gsub("/", "/\n", ., fixed = TRUE) #%>%
    #               #gsub("`", "", .)
    
    #v_equation <- gsub("*", "&times;", v_equation, fixed = TRUE)
    #v_equation <- gsub("+", "&#43;",   v_equation, fixed = TRUE) #%>%
    
    #v_equation <- paste("<div>", v_equation, "</div>")
    
    # Insert formatted equation in summary table
    out[which(out$Sector == v_subsector), v_rfp] <- v_equation
  }
  return(out)
}
```

```{r load_data, error=FALSE, message=FALSE, warning=FALSE, include=FALSE, cache=FALSE}
load("../data/data_checks.RData")

set_flextable_defaults(
  font.size = 8, font.family = "Helvetica",
  font.color = "#000000",
  table.layout = "fixed",
  border.color = "gray",
  padding.top = 3, padding.bottom = 3,
  padding.left = 4, padding.right = 4)
```

# GCAM
```{r include=FALSE}
p_model <- "GCAM5.3_NGFS"

data_avail_summary <- checks[[p_model]]$summary %>% 
  rename(variable = rfp) %>% 
  mutate(rfp = sapply(strsplit(gsub("Diagnostics\\|RFP\\|", "", variable), "\\|"), function(x) x[1])) %>% 
  mutate(tmp = paste0("Diagnostics\\|RFP\\|", rfp, "\\|")) %>% 
  mutate(sector = stringr::str_replace_all(variable, tmp, "")) %>% 
  select(rfp, sector, computable) %>% 
  pivot_wider(names_from = "rfp", values_from = "computable")

v_colnames <- c("Sector", "Direct emissions cost", "Indirect cost", "Low-carbon capital expenditure", "Revenue")
names(data_avail_summary) <- v_colnames
```

## Energy Supply
### Production
```{r echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
v_sector <- "Energy Supply|Production"
v_sector_escaped <- gsub("\\|", "\\\\|", v_sector)

table_summary <- data_avail_summary %>%
  filter(grepl(v_sector_escaped, Sector)) #%>%
  format_table_summary(v_sector_escaped, checks[[p_model]], equations)

table_summary <- table_summary %>%
  mutate(Sector = gsub(paste0(v_sector_escaped, "\\|"), "", Sector)) %>%
  mutate(Sector = ifelse(Sector == v_sector, "Total", Sector))

ft <- flextable(table_summary) %>% 
  theme_vanilla()

ft
```

